---
title: "Cyclistic"
author: "Susan"
date: "6/29/2021"
output:
  html_document: default
  pdf_document: default
---
# Install Packages
```{r load packages, echo=TRUE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(ggplot2)
```


# Set Working Directory and Load Data
```{r load data, warning=FALSE}
setwd("/Users/Suze/Cyclistic Data <20MB")
q4_2019 <- read_csv("Divvy_Trips/Divvy_Trips_2019_Q4.csv")
q1_2018 <- read_csv("Divvy_Trips/Divvy_Trips_2018_Q1.csv")
q4_2018 <- read_csv("Divvy_Trips/Divvy_Trips_2018_Q4.csv")
q1_2020 <- read_csv("Divvy_Trips/Divvy_Trips_2020_Q1.csv")
```

# Combine Data 
```{r combine data, echo=TRUE, warning=FALSE}

## Compare the column names of each file
colnames(q4_2019)
colnames(q1_2018)
colnames(q4_2018)
colnames(q1_2020)

## Rename the columns to align with most recent naming system
(q4_2019 <- rename(q4_2019
                   ,ride_id = trip_id
                   ,rideable_type = bikeid 
                   ,started_at = start_time  
                   ,ended_at = end_time  
                   ,start_station_name = from_station_name 
                   ,start_station_id = from_station_id 
                   ,end_station_name = to_station_name 
                   ,end_station_id = to_station_id 
                   ,member_casual = usertype))

(q1_2018 <- rename(q1_2018
                   ,ride_id = '01 - Rental Details Rental ID'
                   ,rideable_type = '01 - Rental Details Bike ID'
                   ,started_at = '01 - Rental Details Local Start Time'
                   ,ended_at = '01 - Rental Details Local End Time'  
                   ,start_station_name = '03 - Rental Start Station Name' 
                   ,start_station_id = '03 - Rental Start Station ID' 
                   ,end_station_name = '02 - Rental End Station Name' 
                   ,end_station_id = '02 - Rental End Station ID'
                   ,member_casual = 'User Type'
                   ))

(q4_2018 <- rename(q4_2018
                   ,ride_id = trip_id
                   ,rideable_type = bikeid 
                   ,started_at = start_time  
                   ,ended_at = end_time  
                   ,start_station_name = from_station_name 
                   ,start_station_id = from_station_id 
                   ,end_station_name = to_station_name 
                   ,end_station_id = to_station_id 
                   ,member_casual = usertype))

## Inspect dataframes

str(q1_2018)
str(q1_2020)
str(q4_2018)
str(q4_2019)

## Change ride_id and rideable_type to chr

q1_2018 <-  mutate(q1_2018, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type)) 
q4_2018 <-  mutate(q4_2018, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type)) 
q4_2019 <-  mutate(q4_2019, ride_id = as.character(ride_id)
                   ,rideable_type = as.character(rideable_type)) 

## Combine datasets into one dataframe

all_trips <- bind_rows(q1_2018, q1_2020, q4_2018, q4_2019)

## Remove unnecessary columns

all_trips <- all_trips %>%  
  select(-c(start_lat, start_lng, end_lat, end_lng, birthyear, gender, "01 - Rental Details Duration In Seconds Uncapped", "05 - Member Details Member Birthday Year", "Member Gender", "tripduration"))

```

# Clean & Add Data to Prepare for Analysis
```{r clean and add, echo=TRUE, warning=FALSE}

## Look at new table
colnames(all_trips)
nrow(all_trips)
dim(all_trips)
head(all_trips)
str(all_trips)
summary(all_trips)

## Inspect labels for 'member_casual', consolidate to two
unique(all_trips[c("member_casual")])
table(all_trips$member_casual)
all_trips <-  all_trips %>% 
  mutate(member_casual = recode(member_casual
                           ,"Subscriber" = "member"
                           ,"Customer" = "casual"))
table(all_trips$member_casual)

## Add descriptive columns for each ride (date, month, day, year) so we can 
## aggregate in a more helpful way

all_trips$date <- as.Date(all_trips$started_at) 
all_trips$month <- format(as.Date(all_trips$date), "%m")
all_trips$day <- format(as.Date(all_trips$date), "%d")
all_trips$year <- format(as.Date(all_trips$date), "%Y")
all_trips$day_of_week <- format(as.Date(all_trips$date), "%A")
head(all_trips)

## Add a column for ride_length (in seconds)
all_trips$ride_length <- difftime(all_trips$ended_at,all_trips$started_at)
str(all_trips)
is.numeric(all_trips$ride_length)
all_trips$ride_length <- as.numeric(as.character(all_trips$ride_length))
is.numeric(all_trips$ride_length)

## Remove bad data (bikes being checked for quality or negative ride time). 
### Create V2 version of dataframe
all_trips_v2 <- all_trips[!(all_trips$start_station_name == "HQ QR" | all_trips$ride_length<0),]

```

# Descriptive Analysis
```{r descriptive analysis, echo=TRUE, warning=FALSE}

## Look at ride_length
summary(all_trips_v2$ride_length)

## Compare members to casual riders
aggregate(all_trips_v2$ride_length ~ all_trips_v2$member_casual, FUN = mean)
aggregate(all_trips_v2$ride_length ~ all_trips_v2$member_casual, FUN = median)
aggregate(all_trips_v2$ride_length ~ all_trips_v2$member_casual, FUN = max)
aggregate(all_trips_v2$ride_length ~ all_trips_v2$member_casual, FUN = min)

## Average ride time by day for members vs casual riders
all_trips_v2$day_of_week <- ordered(all_trips_v2$day_of_week, levels=c("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"))
aggregate(all_trips_v2$ride_length ~ all_trips_v2$member_casual + all_trips_v2$day_of_week, FUN = mean)

## Analyze by type and weekday
all_trips_v2 %>% 
  mutate(weekday = wday(started_at, label = TRUE)) %>%  
  group_by(member_casual, weekday) %>%  
  summarise(number_of_rides = n()							
  ,average_duration = mean(ride_length)) %>% 		
  arrange(member_casual, weekday)								

## Viz - number of rides by rider type
all_trips_v2 %>% 
  mutate(weekday = wday(started_at, label = TRUE)) %>% 
  group_by(member_casual, weekday) %>% 
  summarise(number_of_rides = n()
            ,average_duration = mean(ride_length)) %>% 
  arrange(member_casual, weekday)  %>% 
  ggplot(aes(x = weekday, y = number_of_rides, fill = member_casual)) +
  geom_col(position = "dodge")

## Viz - average duration 
all_trips_v2 %>% 
  mutate(weekday = wday(started_at, label = TRUE)) %>% 
  group_by(member_casual, weekday) %>% 
  summarise(number_of_rides = n()
            ,average_duration = mean(ride_length)) %>% 
  arrange(member_casual, weekday)  %>% 
  ggplot(aes(x = weekday, y = average_duration, fill = member_casual)) +
  geom_col(position = "dodge")

## Export summary file
counts <- all_trips_v2 %>% 
  mutate(weekday = wday(started_at, label = TRUE)) %>%  
  group_by(member_casual, weekday) %>%  
  summarise(number_of_rides = n()                           
  ,average_duration = mean(ride_length)) %>%        
  arrange(member_casual, weekday)  
write.csv(counts, file = '~/number_of_rides_avg_ride_length.csv')
```
